### ISSUE TITLE
Webpack dependency warnings in 0.3.22

### ISSUE THREAD

**Issue by pReya** [peers/peerjs#484] opened 2019-02-20 13:32 UTC
Hey,

after upgrading to 0.3.22 I get two webpack warnings, that I've never seen before. I'm using create-react-app to build my React app.

```
Compiled with warnings.

./node_modules/peerjs/dist/peerjs.min.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/peerjs/dist/peerjs.min.js
Critical dependency: the request of a dependency is an expression
```

Unfortunately there are no line numbers in the output and I don't know enough about the webpack process to narrow this down. Also googling leads to many different causes for these warnings. Can anyone point me in the right direction, where these warnings come from?

Thanks!

**Comment by kidandcat** [comment] 2019-02-21 00:53
are you parsing node_modules with webpack?

**Comment by pReya** [comment] 2019-02-21 08:06
Thanks for your answer @kidandcat. Unfortunately giving up CRA is not an option for me currently, too many dependencies, too little time.

However from your links I don't see that this is a problem with CRA, but rather with webpack. I'd still like to understand the source of this problem. Any idea, where in the code this is coming from?

**Comment by kidandcat** [comment] 2019-02-21 08:22
It is probably coming from how parcel is bundling the package and dependencies, it is probably doing something like require(package) where:
```
for(p of packages){
  require(p)
}
```

And webpack don't like that because he cannot find which dependency is trying to be loaded.

Anyway webpack shouldn't be analyzing node_modules. So yes, it comes from webpack, but it is probably caused by the create-react-app's webpack configuration.

So you may fix it if you do an eject and plays with the webpack configuration.

**Comment by pReya** [comment] 2019-02-21 08:23
Thanks! Very helpful information. Will try to dig deeper.

**Comment by kidandcat** [comment] 2019-03-11 17:37
I'm closing this as the issue is not in PeerJS

**Closed by kidandcat** 2019-03-11 17:37 UTC
