### ISSUE TITLE
The remote video is not displaying when the local stream video: false

### ISSUE THREAD

**Issue by kkrishalee** [peers/peerjs#967] opened 2022-06-02 03:08 UTC
I am using peerjs to create a video conference call and one of my side doesn't have webcam and the same side answer the call cannot see the remote video. When the webcam doesn't support side initiate the call can see the remote video. When the webcam doesn't support this throws the exception to no media devices found. So I try the server application with video:true and localhost with video:false

**This is my call answer**
```
public async enableCallAnswer(peerId) {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: false,
        audio: true,
      });
      this.localStreamBs.next(stream);

      this.peer.on('call', async (call) => {
        this.mediaCall = call;
        this.isCallStartedBs.next(true);

        this.mediaCall.answer(stream);
        this.mediaCall.on('stream', (remoteStream) => {
          this.remoteStreamBs.next(remoteStream);
        });
        this.mediaCall.on('error', (err) => {
          this.snackBar.openSnackBar({
            message: err,
            type: 'failed',
          });
          this.isCallStartedBs.next(false);
          console.error(err);
        });
        this.mediaCall.on('close', () => this.onCallClose());
      });
    } catch (ex) {
      console.error(ex);
      this.snackBar.openSnackBar({
        message: ex,
        type: 'failed',
      });
      this.isCallStartedBs.next(false);
    }
  }
```

**This is my start call function**
```
public async establishMediaCall(remotePeerId: string) {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: false,
        audio: true,
      });

      const connection = this.peer.connect(remotePeerId);
      connection.on('error', (err) => {
        console.error(err);
        this.snackBar.openSnackBar({
          message: err,
          type: 'failed',
        });
      });

      this.mediaCall = this.peer.call(remotePeerId, stream);
      if (!this.mediaCall) {
        const errorMessage = 'Unable to connect to remote peer';
        this.snackBar.openSnackBar({
          message: errorMessage,
          type: 'failed',
        });
        throw new Error(errorMessage);
      }
      this.localStreamBs.next(stream);
      this.isCallStartedBs.next(true);

      this.mediaCall.on('stream', (remoteStream) => {
        this.remoteStreamBs.next(remoteStream);
      });
      this.mediaCall.on('error', (err) => {
        this.snackBar.openSnackBar({
          message: err,
          type: 'failed',
        });
        console.error(err);
        this.isCallStartedBs.next(false);
      });
      this.mediaCall.on('close', () => this.onCallClose());
    } catch (ex) {
      console.error(ex);
      this.snackBar.openSnackBar({
        message: ex,
        type: 'failed',
      });
      this.isCallStartedBs.next(false);
    }
  }
```

**Comment by jonasgloning** [comment] 2022-06-02 13:55
I think this is a duplicate of #967. There’s a workaround https://github.com/peers/peerjs/issues/944#issuecomment-1123757598

**Closed by jonasgloning** 2022-06-02 13:55 UTC
