### ISSUE TITLE
Failed to set local offer sdp: Called in wrong state: STATE_RECEIVEDINITIATE

### ISSUE THREAD

**Issue by letchoo** [peers/peerjs#286] opened 2015-05-06 03:19 UTC
This issue occurs at times when Firefox v38 makes an attempt to call Chrome v42 and with Temasys AdapterJS integration when IE v11 is the one starting the call with Chrome v42.

**Comment by semigroupoid** [comment] 2015-05-06 21:03
This might be a duplicate of #269. Does the error actually cause peerjs to stop working?

**Comment by letchoo** [comment] 2015-05-07 02:27
Hi @semigroupoid, yes it does. There wasn't a video stream connection.

**Comment by Ashwinkrishna** [comment] 2015-05-26 07:07
Hi I also got the same exception . Can anyone help me in fixing it .

**Comment by chynonm** [comment] 2015-07-17 15:26
Just had this happen now.
Using a slightly altered version of peerjs (adding a few things outside the peerconnection or mediastream)
Both computers were connecting fine. Then by accident one of em was unplugged mid call. From then on haven't been able to get the 2 computers to share mediastream again, even after restarting peerjs server and having them refresh ids.

**Comment by khandelwaludit** [comment] 2015-07-31 16:03
Hi,
This issue is happening to me as well
Failed to setLocalDescription, Failed to set local offer sdp. 
called in wrong state STATE_RECEIVED_INITIATE. Is there a workaround for this ?

**Comment by chynonm** [comment] 2015-08-03 14:07
When it happens the way I fix it is restarting the computer that didn't crash, my understanding is it's probably storing some ice candidates and trying to connect the fastest way possible while the other side isn't prepared yet. 

Didn't try a simple browser restart though (simple page refresh doesn't work)

**Comment by carterbryden** [comment] 2015-08-23 08:11
I'm getting this as well, but on Chrome to Chrome connections. Doesn't seem to prevent the clients from connecting OK however.

**Comment by W0lfEagle** [comment] 2015-09-13 13:09
Getting the same problem Chrome to Chrome. Any solutions yet?

**Comment by vikrantkjain** [comment] 2016-05-31 14:10
Failed to set local offer sdp: Called in wrong state: STATE_RECEIVEDOFFER

**Comment by mikkelking** [comment] 2016-10-03 05:03
Restarting the (chrome) browser made the problem go away for me, and I was able to make calls again

**Comment by zkryakgul** [comment] 2018-05-03 16:34
**## Failed to set local offer sdp: Called in wrong state: kHaveRemoteOffer**

in android native WebChromeClient.  Any solition?

**Comment by AntonLebiodkin** [comment] 2018-05-28 18:30
+1, have `kHaveRemoteOffer`  error, any solutions?

**Comment by Sreekanthp74** [comment] 2018-07-16 06:49
Am also getting the same error 

peer.min.js:1 PeerJS:  ERROR Error: (OperationError) Failed to set local offer sdp: Called in wrong state: kHaveRemoteOffer 
peer.min.js:1 PeerJS:  Failed to setLocalDescription,  (OperationError) Failed to set local offer sdp: Called in wrong state: kHaveRemoteOffer

Any solution for this?

**Comment by zkryakgul** [comment] 2018-07-16 07:04
https://gitlab.com/zkry.akgul/peerjs

Use this instead of orginal lib. I made little touchs to lib files and
seems like problem solved.
------------------------
Zekeriya AKGÜL


Sreekanthp74 <notifications@github.com>, 16 Tem 2018 Pzt, 09:49 tarihinde
şunu yazdı:

**Comment by kidandcat** [comment] 2018-07-16 07:49
Could you test with the latest build from master branch? in "dist" folder

**Comment by zkryakgul** [comment] 2018-07-16 09:01
Nope i couldn't. I work on it couple months ago and use it my small range
project. It was worked for me.

16 Tem 2018 Pzt 10:49 tarihinde Jairo Caro-Accino Viciana <
notifications@github.com> şunu yazdı:

**Comment by Sreekanthp74** [comment] 2018-07-19 11:03
Thanks @zkryakgul , @kidandcat 
I checkout the latest peer.mim.js file and its working fine now.

**Comment by kidandcat** [comment] 2018-07-19 11:45
Mmm, it should be the same file, maybe your browser is catching it with an older version.

Anyway, feel free to reopen if you get the error again. Also I published the changes to NPM so you can use latest version from NPM now.

**Closed by kidandcat** 2018-07-19 11:45 UTC

**Comment by fibin** [comment] 2018-08-20 14:29
Now I have this issue: "OperationError: Failed to set local offer sdp: Called in wrong state: kHaveRemoteOffer". Trying to make connection between two browsers on one computer

**Comment by kidandcat** [comment] 2018-08-20 14:35
Which PeerJS are you using?

**Comment by fibin** [comment] 2018-08-20 14:36
@kidandcat 0.3.14

**Comment by kidandcat** [comment] 2018-08-20 14:41
Update it, latest is 0.3.16

**Comment by fibin** [comment] 2018-08-20 14:46
@kidandcat the error has gone! but no still no audio.
here is how I make call:
`navigator.getUserMedia({audio: true, video: true}, function(stream){
      var call = this.peer.call(this.idToConnect, stream);
      call.on('stream', function(stream) {
        console.log('STREAM');
        console.log(stream);
      })
    },
    err => console.log(err));`

and this is how I revieve it:
`  this.peer.on('call', function(call) {
    navigator.getUserMedia({
    audio: true,
    video: true
    }, function(stream) {
    call.answer(stream);
    call.on('stream', function(stream) {
      console.log('RESPONED CALL');
      console.log(stream)
    });
    }, function(error) {
    //...
    });
    });`
