### ISSUE TITLE
Error: ID is taken: when internet is disconnected and reconnected again.

### ISSUE THREAD

**Issue by pratikraj26** [peers/peerjs#294] opened 2015-06-08 19:10 UTC
I got following error message when i try to connect to the peer server when the internet is reconnected after disconnection. I am using a custom peer id for the peer connection.

PeerJS: Socket open
PeerJS: ERROR Aborting!
PeerJS: ERROR Error: ID `323` is taken
PeerJS: Socket closed.
PeerJS: ERROR Error: Lost connection to server.

I think the server keeps the id for too long. Is there any way to forcefully destroy the connection with specific peer id ?

**Comment by prophittcorey** [comment] 2015-07-15 21:11
I would investigate the `peer.destroy()` method.

**Comment by forrana** [comment] 2017-06-23 13:23
looks like dub of [224](https://github.com/peers/peerjs/issues/224)

**Comment by LucaColombi** [comment] 2018-08-14 10:14
Same problem after 4 years, I suppose there is a maintainance problem :|

Is there a id timeout or a way to stimulate the real taken status of an ID?

**Comment by kidandcat** [comment] 2018-08-14 10:42
duplicate of #224

**Closed by kidandcat** 2018-08-14 10:42 UTC
